export const EMPLOYEES = [
  {
    id: "emp-001",
    name: "Marta Rinaldi",
    role: "HR Lead",
    department: "People",
    status: "active",
    email: "marta.rinaldi@northwave.test",
    phone: "+39 345 100 2201",
    location: "Milano HQ",
    lastAction: "Updated policy pack",
  },
  {
    id: "emp-002",
    name: "Luca Marchetti",
    role: "Operations Manager",
    department: "Operations",
    status: "active",
    email: "luca.marchetti@northwave.test",
    phone: "+39 345 100 2202",
    location: "Torino Site",
    lastAction: "Checked in 08:41",
  },
  {
    id: "emp-003",
    name: "Sara Pinto",
    role: "Finance Specialist",
    department: "Finance",
    status: "inactive",
    email: "sara.pinto@northwave.test",
    phone: "+39 345 100 2203",
    location: "Remote",
    lastAction: "Pending document review",
  },
];
