# Generated by Django 6.0.4 on 2026-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_deleted_at_company_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('company_created', 'Company Created'), ('company_registered', 'Company Registered'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_soft_deleted', 'Company Soft Deleted'), ('company_access_reset', 'Company Access Reset')], max_length=50),
        ),
    ]
