# Generated by Django 6.0.4 on 2026-04-17 20:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cleanup_duplicate_company_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('check_in', 'Check In'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('check_out', 'Check Out')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
    ]
