# Generated by Django 6.0.4 on 2026-04-17 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('company_created', 'Company Created'), ('company_registered', 'Company Registered'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_soft_deleted', 'Company Soft Deleted'), ('company_access_reset', 'Company Access Reset'), ('company_user_created', 'Company User Created'), ('company_user_updated', 'Company User Updated'), ('company_user_disabled', 'Company User Disabled'), ('role_assigned', 'Role Assigned'), ('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('employee_suspended', 'Employee Suspended'), ('employee_reactivated', 'Employee Reactivated'), ('password_reset', 'Password Reset'), ('invite_generated', 'Invite Generated'), ('attendance_corrected', 'Attendance Corrected'), ('attendance_day_approved', 'Attendance Day Approved'), ('attendance_month_approved', 'Attendance Month Approved'), ('anomaly_reviewed', 'Anomaly Reviewed'), ('consultant_access', 'Consultant Access')], max_length=50),
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('reason', models.TextField()),
                ('original_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='users.company')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='users.timeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDayReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review_needed', 'Review Needed'), ('approved', 'Approved'), ('corrected', 'Corrected')], default='draft', max_length=20)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_days', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_day_reviews', to='users.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_days', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_day_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user__email'],
                'unique_together': {('company', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('approved', 'Approved'), ('closed', 'Closed'), ('exported', 'Exported')], default='open', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_periods', to='users.company')),
            ],
            options={
                'ordering': ['-year', '-month', 'company__name'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
