# Generated by Django 6.0.4 on 2026-04-17 21:43

import django.db.models.deletion
import uuid
import secrets
from django.conf import settings
from django.db import migrations, models


def populate_company_public_ids(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    existing_ids = set(Company.objects.exclude(public_id__isnull=True).values_list('public_id', flat=True))

    for company in Company.objects.filter(public_id__isnull=True):
        candidate = None
        while not candidate or candidate in existing_ids:
            candidate = secrets.token_urlsafe(9).replace('-', '').replace('_', '')[:14].upper()
        company.public_id = candidate
        company.save(update_fields=['public_id'])
        existing_ids.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_timeentry_created_by_timeentry_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(populate_company_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('company_created', 'Company Created'), ('company_registered', 'Company Registered'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_soft_deleted', 'Company Soft Deleted'), ('company_access_reset', 'Company Access Reset'), ('company_user_created', 'Company User Created'), ('company_user_updated', 'Company User Updated'), ('company_user_disabled', 'Company User Disabled'), ('role_assigned', 'Role Assigned'), ('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('employee_suspended', 'Employee Suspended'), ('employee_reactivated', 'Employee Reactivated'), ('password_reset', 'Password Reset'), ('invite_generated', 'Invite Generated'), ('attendance_corrected', 'Attendance Corrected'), ('attendance_day_approved', 'Attendance Day Approved'), ('attendance_month_approved', 'Attendance Month Approved'), ('anomaly_reviewed', 'Anomaly Reviewed'), ('consultant_access', 'Consultant Access'), ('consultant_link_requested', 'Consultant Link Requested'), ('consultant_link_approved', 'Consultant Link Approved'), ('consultant_link_rejected', 'Consultant Link Rejected'), ('consultant_link_removed', 'Consultant Link Removed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('platform_owner', 'Platform Owner'), ('company_owner', 'Company Owner'), ('company_admin', 'Company Admin'), ('hr_manager', 'HR Manager'), ('manager', 'Manager'), ('external_consultant', 'External Consultant'), ('labor_consultant', 'Labor Consultant'), ('safety_consultant', 'Safety Consultant'), ('employee', 'Employee')], default='employee', max_length=30),
        ),
        migrations.CreateModel(
            name='ConsultantCompanyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_company', 'Pending Company'), ('pending_consultant', 'Pending Consultant'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=24)),
                ('requested_by', models.CharField(choices=[('consultant', 'Consultant'), ('company', 'Company')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_company_links', to='users.company')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_company_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('consultant', 'company')},
            },
        ),
    ]
