# Generated by Django 6.0.4 on 2026-04-18 20:04

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_public_id_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('company_created', 'Company Created'), ('company_registered', 'Company Registered'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_soft_deleted', 'Company Soft Deleted'), ('company_access_reset', 'Company Access Reset'), ('company_user_created', 'Company User Created'), ('company_user_updated', 'Company User Updated'), ('company_user_disabled', 'Company User Disabled'), ('role_assigned', 'Role Assigned'), ('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('employee_suspended', 'Employee Suspended'), ('employee_reactivated', 'Employee Reactivated'), ('password_reset', 'Password Reset'), ('invite_generated', 'Invite Generated'), ('attendance_corrected', 'Attendance Corrected'), ('attendance_day_approved', 'Attendance Day Approved'), ('attendance_month_approved', 'Attendance Month Approved'), ('anomaly_reviewed', 'Anomaly Reviewed'), ('consultant_access', 'Consultant Access'), ('consultant_link_requested', 'Consultant Link Requested'), ('consultant_link_approved', 'Consultant Link Approved'), ('consultant_link_rejected', 'Consultant Link Rejected'), ('consultant_link_removed', 'Consultant Link Removed'), ('document_uploaded', 'Document Uploaded'), ('document_downloaded', 'Document Downloaded'), ('document_archived', 'Document Archived'), ('payroll_created', 'Payroll Created'), ('payroll_status_changed', 'Payroll Status Changed'), ('payroll_approved', 'Payroll Approved'), ('payroll_correction_requested', 'Payroll Correction Requested'), ('payroll_delivered', 'Payroll Delivered'), ('unauthorized_access_attempt', 'Unauthorized Access Attempt')], max_length=50),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payroll_document', 'Payroll Document'), ('employee_document', 'Employee Document'), ('company_document', 'Company Document'), ('safety_document', 'Safety Document'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=users.models.protected_document_upload_to)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('company_only', 'Company Only'), ('consultant_only', 'Consultant Only'), ('company_and_consultant', 'Company and Consultant'), ('employee_only', 'Employee Only'), ('employee_and_company', 'Employee and Company'), ('employee_company_consultant', 'Employee Company Consultant')], default='company_and_consultant', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.employeeprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_documents', 'Waiting Documents'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready For Review'), ('approved_by_company', 'Approved By Company'), ('delivered_to_employee', 'Delivered To Employee'), ('correction_requested', 'Correction Requested'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('notes_company', models.TextField(blank=True)),
                ('notes_consultant', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('period_reference', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='users.employeeprofile')),
                ('labor_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-updated_at'],
                'unique_together': {('company', 'employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_workflow', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('attachment', 'Attachment'), ('final_payslip', 'Final Payslip')], default='attachment', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_links', to='users.document')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='users.payrollrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('payroll_run', 'document')},
            },
        ),
    ]
