# Generated by Django 6.0.4 on 2026-04-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_seed_payroll_document_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Successo'), ('warning', 'Avviso'), ('error', 'Errore'), ('attention', 'Richiede attenzione')], default='info', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorita')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letta')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='URL azione')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Letto il')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx')],
            },
        ),
    ]
