# Generated by Django 6.0.4 on 2026-04-19 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('currency_symbol', models.CharField(default='€', max_length=5)),
                ('yearly_discount_percent', models.PositiveIntegerField(default=20, help_text='Sconto per pagamento annuale')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Giorni di prova gratuiti')),
                ('terms_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Pricing',
                'verbose_name_plural': 'Configurazioni Pricing',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensile'), ('yearly', 'Annuale')], max_length=20)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Prezzo in centesimi (es. 4900 = €49.00)')),
                ('setup_fee_cents', models.PositiveIntegerField(default=0, help_text='Costo una tantum di setup')),
                ('max_employees', models.PositiveIntegerField(default=10, help_text='Numero massimo di dipendenti')),
                ('max_companies', models.PositiveIntegerField(default=1, help_text='Numero massimo di aziende gestibili (per consulenti)')),
                ('include_payroll', models.BooleanField(default=True)),
                ('include_attendance', models.BooleanField(default=True)),
                ('include_documents', models.BooleanField(default=True)),
                ('include_safety', models.BooleanField(default=False)),
                ('include_reports', models.BooleanField(default=False)),
                ('include_api_access', models.BooleanField(default=False)),
                ('include_priority_support', models.BooleanField(default=False)),
                ('include_white_label', models.BooleanField(default=False)),
                ('extra_employee_price_cents', models.PositiveIntegerField(default=100, help_text='Costo per dipendente extra')),
                ('is_active', models.BooleanField(default=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Mostra come piano consigliato')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.TextField(blank=True, help_text='Lista feature separata da newline')),
                ('limitations', models.TextField(blank=True, help_text='Limitazioni del piano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Piano Tariffario',
                'verbose_name_plural': 'Piani Tariffari',
                'ordering': ['display_order', 'plan_type', 'billing_cycle'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('company_created', 'Company Created'), ('company_registered', 'Company Registered'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_soft_deleted', 'Company Soft Deleted'), ('company_access_reset', 'Company Access Reset'), ('company_user_created', 'Company User Created'), ('company_user_updated', 'Company User Updated'), ('company_user_disabled', 'Company User Disabled'), ('role_assigned', 'Role Assigned'), ('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('employee_suspended', 'Employee Suspended'), ('employee_reactivated', 'Employee Reactivated'), ('password_reset', 'Password Reset'), ('invite_generated', 'Invite Generated'), ('attendance_corrected', 'Attendance Corrected'), ('attendance_day_approved', 'Attendance Day Approved'), ('attendance_month_approved', 'Attendance Month Approved'), ('anomaly_reviewed', 'Anomaly Reviewed'), ('consultant_access', 'Consultant Access'), ('consultant_link_requested', 'Consultant Link Requested'), ('consultant_link_approved', 'Consultant Link Approved'), ('consultant_link_rejected', 'Consultant Link Rejected'), ('consultant_link_removed', 'Consultant Link Removed'), ('document_uploaded', 'Document Uploaded'), ('document_downloaded', 'Document Downloaded'), ('document_archived', 'Document Archived'), ('payroll_created', 'Payroll Created'), ('payroll_status_changed', 'Payroll Status Changed'), ('payroll_approved', 'Payroll Approved'), ('payroll_correction_requested', 'Payroll Correction Requested'), ('payroll_delivered', 'Payroll Delivered'), ('unauthorized_access_attempt', 'Unauthorized Access Attempt'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('leave_type', models.CharField(choices=[('vacation', 'Ferie'), ('sick', 'Malattia'), ('personal', 'Permesso personale'), ('maternity', 'Maternita'), ('paternity', 'Paternita'), ('bereavement', 'Lutto'), ('unpaid', 'Non retribuito'), ('other', 'Altro')], default='vacation', max_length=20)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('max_days_per_year', models.PositiveIntegerField(default=0)),
                ('max_consecutive_days', models.PositiveIntegerField(default=0)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('icon', models.CharField(default='calendar', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='users.company')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('approved', 'Approvato'), ('rejected', 'Rifiutato'), ('cancelled', 'Annullato')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('half_day_start', models.BooleanField(default=False)),
                ('half_day_end', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.employeeprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.employeeprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='users.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
