# Generated by Django 6.0.4 on 2026-04-29 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_automation_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ricevuta Documento', 'verbose_name_plural': 'Ricevute Documenti'},
        ),
        migrations.AlterModelOptions(
            name='signaturelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log Firma', 'verbose_name_plural': 'Log Firme'},
        ),
        migrations.AlterModelOptions(
            name='signaturerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Richiesta Firma', 'verbose_name_plural': 'Richieste Firma'},
        ),
        migrations.AlterModelOptions(
            name='ssosession',
            options={'ordering': ['-created_at'], 'verbose_name': 'SSO Session', 'verbose_name_plural': 'SSO Sessions'},
        ),
        migrations.AlterModelOptions(
            name='ssouserlink',
            options={'verbose_name': 'SSO User Link', 'verbose_name_plural': 'SSO User Links'},
        ),
        migrations.RemoveField(
            model_name='onboardingtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('sickness', 'Malattia'), ('maternity', 'Maternita'), ('paternity', 'Paternita'), ('injury', 'Infortunio'), ('other', 'Altro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_storage_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Storage currently used in MB', max_digits=10),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('sickness', 'Malattia'), ('maternity', 'Maternita'), ('paternity', 'Paternita'), ('injury', 'Infortunio'), ('other', 'Altro')], default='sickness', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='visit_type',
            field=models.CharField(choices=[('periodic', 'Periodica'), ('pre_employment', 'Pre-assunzione'), ('return_to_work', 'Rientro al lavoro'), ('follow_up', 'Follow-up'), ('fitness_test', 'Test di idoneita'), ('other', 'Altro')], default='periodic', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='radius_meters',
            field=models.PositiveIntegerField(default=100, help_text='Geofence radius in meters'),
        ),
        migrations.AlterField(
            model_name='offlinetimeentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='currency_symbol',
            field=models.CharField(default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Free trial days'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='yearly_discount_percent',
            field=models.PositiveIntegerField(default=20, help_text='Discount for annual payment'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='extra_employee_price_cents',
            field=models.PositiveIntegerField(default=100, help_text='Cost per extra employee'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features_list',
            field=models.TextField(blank=True, help_text='Feature list separated by newline'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Show as recommended plan'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='limitations',
            field=models.TextField(blank=True, help_text='Plan limitations'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='max_companies',
            field=models.PositiveIntegerField(default=1, help_text='Max companies (for consultants)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='max_employees',
            field=models.PositiveIntegerField(default=10, help_text='Maximum employees allowed'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=50, help_text='Maximum file size in MB'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='max_storage_mb',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum storage in MB'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Price in cents (e.g., 4900 = EUR49.00)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='setup_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='One-time setup fee'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetycourse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetyinspection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Check-in latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Check-in longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
